feat(sourceselector): highlight clicks on buttons and CTAs
adobe/helix-rum-enhancer pull request #115
Opened 2024-01-17 19:43 UTC by ddragosd

Reflecting the change from #108 into the `main` branch.  

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

2024-01-18 08:28 UTC, chicharr requested changes

2024-01-18 08:28 UTC, chicharr commented on src/index.js
> +    return blockName ? `.${blockName} .button` : '.button';
`blockName` is always undefined ;) 
you need to move the declaration in line 48 out of the `if`

2024-01-18 20:09 UTC, ddragosd commented on src/index.js
> +    return blockName ? `.${blockName} .button` : '.button';
@chicharr such a good catch ! thanks so much for capturing this! I totally messed up my `cherry-pick`

2024-01-19 11:20 UTC, chicharr approved these changes
LGTM

2024-03-04 08:58 UTC, merged