feat(viewmedia): expand view media tracking to all images that are there at render time
adobe/helix-rum-enhancer pull request #196
Opened 2024-06-10 15:39 UTC by trieloff

2024-06-10 21:47 UTC, chicharr approved these changes

2024-06-11 07:51 UTC, kptdobe requested changes

2024-06-11 07:51 UTC, kptdobe commented on test/img.test.html
> +          });
This is makes the test unstable. You can use the `done` approach (`done` function in the params that you call when onload and your tests are executed)

2024-06-11 08:32 UTC, kptdobe commented on test/img.test.html
> +          });
I have re-read the test and I assume you need to wait "a little bit" for sampleRUM to be called and executed.

2024-06-11 08:50 UTC, merged