test advanced checkpoints
adobe/helix-rum-enhancer pull request #230
Opened 2024-07-04 17:47 UTC by trieloff

- **test(index): test block visibility, resource loading**
- **test(index): add test for form submissions**

2024-07-08 07:08 UTC, kptdobe requested changes

2024-07-08 07:08 UTC, kptdobe commented on test/it/loadblock.test.html
> +          assert(window.called.some((call) => call.checkpoint === 'viewmedia'), 'viewmedia checkpoint missing');
This is a bad practice: the tests share the same execution context, i.e. they can interfere between each others. This one can for example trigger a `missingresource` you do not check here. If implementation for next test is broken (i.e. fetch does not fire a `missingresouce`, test will be successful but implementation is wrong.

Several todos:
- before / after each test, clean up the `called` stack
- in each test, test for exact equality - if order is random, at least test for window.called.length === 4

If this is not doable in one file, split into multiple files

2024-07-08 07:08 UTC, kptdobe commented on test/it/loadblock.test.html
> +          assert(window.called.some((call) => call.checkpoint === 'missingresource'), 'missingresource checkpoint missing');
You are testing `missingresource` in a `loadblock` test file. Either rename the file or move to dedicated test file.

2024-07-08 07:08 UTC, kptdobe commented on test/it/loadblock.test.html
> +        assert(window.called.some((call) => call.checkpoint === 'formsubmit'), 'formsubmit checkpoint missing');
Same, testing `formsubmit` in `loadblock`file...

2024-07-08 07:08 UTC, kptdobe commented on test/it/block.plain.html
> +<div>
Move file into a `fixtures` subfolder to separate test files and resources (same for image)

2024-08-15 08:20 UTC, trieloff commented on test/it/block.plain.html
> +<div>
done

2024-08-15 08:20 UTC, trieloff commented on test/it/loadblock.test.html
> +        assert(window.called.some((call) => call.checkpoint === 'formsubmit'), 'formsubmit checkpoint missing');
done

2024-08-15 08:20 UTC, trieloff commented on test/it/loadblock.test.html
> +          assert(window.called.some((call) => call.checkpoint === 'missingresource'), 'missingresource checkpoint missing');
done

2024-08-15 08:20 UTC, trieloff commented on test/it/loadblock.test.html
> +          assert(window.called.some((call) => call.checkpoint === 'viewmedia'), 'viewmedia checkpoint missing');
I've split it into multiple files

2024-08-15 08:22 UTC, trieloff commented
This brings us up to 98.87% coverage

2024-08-15 10:36 UTC, merged