feat(onetrust): enable on all domains
adobe/helix-rum-enhancer pull request #255
Opened 2024-08-12 10:19 UTC by trieloff

2024-08-12 12:41 UTC, kptdobe requested changes
The split is a good idea and great opportunity to write tests, no ?

2024-08-12 12:43 UTC, kptdobe commented on modules/defaults.js
> +fflags.enabled('example', () => DEFAULT_TRACKING_EVENTS.push('example'));
What is `example` about ? are we going to deploying an `example` checkpoint on some sites ?

2024-08-12 15:02 UTC, trieloff commented on modules/defaults.js
> +fflags.enabled('example', () => DEFAULT_TRACKING_EVENTS.push('example'));
I've kept it in so that we have an example once we need to create a feature flag again (our list of active flags is empty right now) and to keep the test that covers the flags system in working order.

2024-08-12 15:03 UTC, trieloff commented
Everything covered by the split is tested already, and given that I have a couple of test-centric PRs open already, I thought it best not to combine a test expansion with this relatively small change.

2024-08-13 07:16 UTC, kptdobe approved these changes

2024-08-13 13:55 UTC, merged