feat(navigation): add support for `redirect` checkpoint
adobe/helix-rum-enhancer pull request #273
Opened 2024-09-04 13:01 UTC by trieloff

if the visitor arrived on the page via a (server-side) redirect, then
fire a `redirect` checkpoint with the original URL (if CDN supports it)
and the number of redirect hops

see https://cq-dev.slack.com/archives/C07198KKQ07/p1725446009159669

2024-09-09 13:30 UTC, kptdobe requested changes

2024-09-09 13:30 UTC, kptdobe commented on modules/index.js
> +      const from = new URLSearchParams(window.location.search).get('redirect-from');
See slack for discussion on this ugly search param

2024-09-09 13:30 UTC, kptdobe commented on test/it/navigation.test.html
> +                  type: 'navigate',
Missing test for the "ugly search param" use case.

2024-09-19 08:22 UTC, trieloff commented on test/it/navigation.test.html
> +                  type: 'navigate',
Test is now included.

2024-09-19 13:40 UTC, kptdobe approved these changes

2024-09-19 13:40 UTC, kptdobe commented on modules/index.js
> +        sampleRUM('redirect', { source: from, target: redirectCount || 1 });
```suggestion
        sampleRUM('redirect', { source: from || '', target: redirectCount || 1 });
```

`from` might be null

2024-09-20 08:01 UTC, merged