feat(navigate): refine checkpoints for `enter`, `navigate`, `reload`, `back_forward`, and `prerender`, track `visibilityState` - `enter` will now fire for every page open that does not come from the same origin, including direct opens - `reload` tracks reloads or opens from the same exact page - `back_forward` and `prerender` track what's on the tin - `navigate` is all on-site navigation in addition the `document.VisibilityState` is tracked in `target` allowing us to filter non-visible opens that are not performance critical and often throttled
adobe/helix-rum-enhancer pull request #93
Opened 2023-11-17 10:21 UTC by trieloff

2023-11-17 12:21 UTC, chicharr approved these changes
LGTM

2023-11-17 12:21 UTC, chicharr commented on src/index.js
> +  const payload = { source, target: document.visibilityState };
In the `minirum` I added the `visibilityState` in the `top` checkpoint. 
I think I will just move it to the enhancer, in the same way than here

2023-11-17 14:58 UTC, chicharr requested changes

2023-11-17 14:58 UTC, chicharr commented on src/index.js
> +  .observe({ entryTypes: ['navigation'], buffered: true });
This should by:
```suggestion
  .observe({ type: 'navigation', buffered: true });
```
`entryTypes` can't be used together with `buffered`

2023-11-17 16:24 UTC, chicharr approved these changes
LGTM

2023-11-20 11:05 UTC, ramboz approved these changes

2023-11-21 09:01 UTC, merged